django_payment_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("payments/", include("payment.urls"), name="payments"),
]

payment/urls.py
from django.urls import path

from payment.views import create_order, capture_order, payment_success, payment, payment_details

app_name = 'payment'

urlpatterns = [
    path('api/orders/<int:object_id>', create_order, name='create_order'),
    path('api/orders/<str:order_id>/capture/', capture_order, name='capture_order'),

    # path('', payment, name='payment'),  # not a good idea
    path('<int:object_id>/<str:id_request>/', payment, name='payment_linked'),

    # path('success/<str:order_id>/', payment_success, name='success'),  # not a good idea
    path('success/<int:object_id>/<str:order_id>/', payment_success, name='success_linked'),

    path('details/<str:reference_id>/<str:object_id>/<str:order_id>/', payment_details, name='payment_details'),
]

payment/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse


class Payment(models.Model):
    order_id = models.CharField(max_length=255, unique=True)
    reference_id = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=3)
    status = models.CharField(max_length=20)

    linked_object_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    linked_object_id = models.PositiveIntegerField(null=True, blank=True)
    linked_object = GenericForeignKey('linked_object_type', 'linked_object_id')

    # meta data
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.created_at} - {self.order_id} - {self.reference_id} - {self.amount} - {self.currency} - {self.status}"

    def get_order_id(self):
        return self.order_id

    def get_reference_id(self):
        return self.reference_id

    def get_amount(self):
        return self.amount

    def get_currency(self):
        if self.currency == "EUR":
            return "€"
        elif self.currency == "USD":
            return "$"
        else:
            return self.currency

    def get_status(self):
        return self.status

    def get_linked_object(self):
        return self.linked_object

    def get_created_at(self):
        return self.created_at

    def get_updated_at(self):
        return self.updated_at

    def get_total_amount(self):
        return self.amount + self.fee

    def get_fee(self):
        return self.fee

    def get_absolute_url(self):
        return reverse("payment:payment_details",
                       kwargs={"reference_id": self.reference_id, "object_id": self.linked_object_id,
                               "order_id": self.order_id})

    def get_payment_status_css_status(self):
        if self.status == "COMPLETED":
            return "success"
        elif self.status == "APPROVED":
            return "success"
        elif self.status == "CREATED":
            return "warning"
        elif self.status == "SAVED":
            return "warning"
        elif self.status == "PENDING":
            return "warning"
        elif self.status == "REJECTED":
            return "danger"
        elif self.status == "ERROR":
            return "danger"
        elif self.status == "EXPIRED":
            return "danger"
        elif self.status == "CANCELLED":
            return "danger"
        else:
            return "danger"

payment/views.py
import datetime
import json
import logging
import sys
from decimal import Decimal

import requests
from django.apps import apps
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from payment import settings
from payment.email_sender import send_email, notify_admin
from payment.models import Payment
from payment.settings import PAYMENT_MODEL, PAYMENT_BASE_TEMPLATE, PAYMENT_WEBSITE_NAME, PAYMENT_REDIRECT_SUCCESS_URL, \
    PAYMENT_APPLY_PAYPAL_FEES, DEFAULT_EMAIL_MESSAGE, DEFAULT_EMAIL_PAYMENT_SUCCESS_TEMPLATE
from payment.utils import get_paypal_access_token, generate_client_token, calculate_total_amount, get_payment_details

PAYMENT_OBJECT = apps.get_model(PAYMENT_MODEL)

# create logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# configure basicConfig with the formatter, log level, and handlers
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    datefmt='%m/%d/%Y %I:%M:%S %p',
                    level=logging.DEBUG,
                    handlers=[logging.StreamHandler(sys.stdout)])


@csrf_exempt
def create_order(request, object_id):
    if request.method == 'POST':
        funding_source = request.GET.get('funding_source', 'paypal')
        logger.info(f"Funding source received: {funding_source}")
        payment_info = get_object_or_404(PAYMENT_OBJECT, pk=object_id)
        reference_id = f"{payment_info.get_id_request()}"

        environment = settings.PAYMENT_PAYPAL_ENVIRONMENT
        ENDPOINT_URL = "https://api-m.sandbox.paypal.com" if environment == "sandbox" else "https://api-m.paypal.com"
        # Prepare the payload
        logger.info(f"payment_info.get_currency(): {payment_info.get_currency()}")
        logger.info(f"payment_info.get_amount_to_pay(): {payment_info.get_amount_to_pay()}")
        logger.info(f"reference_id: {reference_id}")

        value = calculate_total_amount(amount=payment_info.get_amount_to_pay(), payment_type=funding_source) if PAYMENT_APPLY_PAYPAL_FEES else \
            str(payment_info.get_amount_to_pay())
        currency = payment_info.get_currency() if payment_info.get_currency() else "USD"
        logger.info(f"total amount after fee calculation: {currency} {value}")

        payload = {
            "purchase_units": [
                {
                    "amount": {
                        "currency_code": currency,
                        "value": value,
                    },
                    "reference_id": reference_id,
                }
            ],
            "intent": "CAPTURE",
        }

        logger.info(f"payload: {payload}")

        access_token = get_paypal_access_token(settings.PAYMENT_PAYPAL_CLIENT_ID, settings.PAYMENT_PAYPAL_CLIENT_SECRET,
                                               ENDPOINT_URL)
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {access_token}"
        }

        # Send the create order request to PayPal
        print(f"json dump before create order: {json.dumps(payload)}")
        response = requests.post(f"{ENDPOINT_URL}/v2/checkout/orders", data=json.dumps(payload), headers=headers)

        if response.status_code == 201:
            order_data = response.json()

            payment_ = Payment(
                order_id=order_data["id"],
                reference_id=reference_id,
                amount=payment_info.get_amount_to_pay(),
                fee=Decimal(value=value) - payment_info.get_amount_to_pay(),
                currency=payment_info.get_currency(),
                status=order_data["status"]
            )
            payment_.linked_object = payment_info
            payment_.save()
            return JsonResponse({"id": payment_.order_id, "fee": payment_.get_fee(), "total_amount": payment_.get_total_amount()})
        else:
            return JsonResponse({"error": "Failed to create order"}, status=400)
    else:
        return JsonResponse({"error": "Invalid request method"}, status=405)


@csrf_exempt
def capture_order(request, order_id):  # Change this line
    if request.method == 'POST':
        payment_ = get_object_or_404(Payment, order_id=order_id)  # Change this line
        order_data = {
            "order_id": payment_.get_order_id(),
            "status": "COMPLETED",
        }
        payment_.status = "COMPLETED"
        payment_.save()
        return JsonResponse(order_data)
    else:
        return JsonResponse({"error": "Invalid request method"}, status=405)


def payment(request, object_id, id_request):
    logger.info(f"object_id {object_id} id_request {id_request}")
    payment_info = get_object_or_404(PAYMENT_OBJECT, pk=object_id)
    environment = settings.PAYMENT_PAYPAL_ENVIRONMENT
    endpoint_url = "https://api-m.sandbox.paypal.com" if environment == "sandbox" else "https://api-m.paypal.com"

    access_token = get_paypal_access_token(settings.PAYMENT_PAYPAL_CLIENT_ID, settings.PAYMENT_PAYPAL_CLIENT_SECRET,
                                           endpoint_url)
    client_token = generate_client_token(access_token, endpoint_url)
    total_amount = calculate_total_amount(payment_info.get_amount_to_pay()) if PAYMENT_APPLY_PAYPAL_FEES else str(
        payment_info.get_amount_to_pay())
    fee = Decimal(total_amount) - payment_info.get_amount_to_pay()
    fee_amount = "{:.2f}".format(fee)
    context = {
        "PAYMENT_BASE_TEMPLATE": PAYMENT_BASE_TEMPLATE,
        "PAYMENT_WEBSITE_NAME": PAYMENT_WEBSITE_NAME,
        "client_token": client_token,
        "service": payment_info,
        "object_id": object_id,
        "id_request": id_request,
        "client_id": settings.PAYMENT_PAYPAL_CLIENT_ID,
        "total_amount": total_amount,
        "fee_amount": fee_amount,
    }
    logger.info(f"payment context: {context}")
    return render(request, 'payment/payment.html', context=context)


def payment_success(request, object_id, order_id):
    object_info = get_object_or_404(PAYMENT_OBJECT, pk=object_id)
    object_info.set_paid_status(status=True)
    payment_info = get_object_or_404(Payment, order_id=order_id)
    first_name = object_info.get_user_name()
    company = PAYMENT_WEBSITE_NAME

    common_context = {
        'first_name': first_name,
        'company': company,
        "order_id": order_id,
        "payment_info": payment_info,
    }

    context = {
        **common_context,
        "PAYMENT_BASE_TEMPLATE": PAYMENT_BASE_TEMPLATE,
        "PAYMENT_REDIRECT_SUCCESS_URL": PAYMENT_REDIRECT_SUCCESS_URL,
        "object_info": object_info,
    }
    link = request.build_absolute_uri(payment_info.get_absolute_url())
    message = DEFAULT_EMAIL_MESSAGE or f"Thank you for your payment, it's been received and your booking is now confirmed" \
                                       f"You can view it by clicking <a href='{link}'>here</a> " \
                                       f"We're excited to have you on board! Your order # is {order_id}."

    template_url_email = DEFAULT_EMAIL_PAYMENT_SUCCESS_TEMPLATE or 'email_sender/payment_email.html'

    email_context = {
        **common_context,
        'message': message,
        'current_year': datetime.datetime.now().year,
    }

    admin_email_context = {
        **common_context,
        'payment_info': payment_info,
        'linked_object': payment_info.get_linked_object(),
        'reference_id': payment_info.get_reference_id(),
        "current_date": payment_info.get_created_at().strftime("%B %d, %Y"),
        "user_email": object_info.get_user_email(),
        "status": payment_info.get_payment_status_css_status(),
    }

    # Email the user
    logger.info(f"Email the user: {context}")
    send_email(
        recipient_list=[object_info.get_user_email()], subject="Payment successful",
        template_url=template_url_email, context=email_context
    )
    logger.info(f"Notifying admin for payment details: {context}")
    notify_admin(subject="Payment details for order # {}".format(order_id),
                 template_url="email_sender/notify_admin.html",
                 context=admin_email_context)
    return render(request, 'payment/success.html', context=context)


def payment_details(request, reference_id, object_id, order_id):
    object_info = get_object_or_404(PAYMENT_OBJECT, pk=object_id)
    first_name = object_info.get_user_name()
    user_email = object_info.get_user_email()
    payment_ = get_object_or_404(Payment, order_id=order_id)
    environment = settings.PAYMENT_PAYPAL_ENVIRONMENT
    endpoint_url = "https://api-m.sandbox.paypal.com" if environment == "sandbox" else "https://api-m.paypal.com"
    access_token = get_paypal_access_token(settings.PAYMENT_PAYPAL_CLIENT_ID, settings.PAYMENT_PAYPAL_CLIENT_SECRET,
                                           endpoint_url)
    client_token = generate_client_token(access_token, endpoint_url)
    data = get_payment_details(order_id=order_id, access_token=access_token, endpoint_url=endpoint_url)
    logger.info(f"payment details: {data}")
    linked_object = payment_.linked_object
    context = {
        "PAYMENT_BASE_TEMPLATE": PAYMENT_BASE_TEMPLATE,
        "PAYMENT_WEBSITE_NAME": PAYMENT_WEBSITE_NAME,
        'payment_info': payment_,
        'linked_object': linked_object,
        'reference_id': reference_id,
        "current_date": payment_.get_created_at().strftime("%B %d, %Y"),
        "first_name": first_name,
        "user_email": user_email,
        "status": payment_.get_payment_status_css_status(),
    }
    return render(request, 'payment/payment_details.html', context)

payment/templates/payment/payment.html
{% extends PAYMENT_BASE_TEMPLATE %}
{% load i18n %}
{% load static %}
{% block customCSS %}
<link rel="stylesheet" type="text/css" href="{% static 'css/payment.css' %}"/>
{% endblock %}
{% block title %}
Checkout - {{ PAYMENT_WEBSITE_NAME }}
{% endblock %}
{% block description %}
Checkout payment for the service {{ service.get_name }}
{% endblock %}
{% block scriptHead %}
<script src="https://www.paypal.com/sdk/js?components=buttons,hosted-fields&client-id={{ client_id }}"
        data-client-token="{{ client_token }}"
></script>
{% endblock %}
{% block body %}
<div class="main-container">
<div class="body-container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
         role="alert">{{ message }}
    </div>
    {% endfor %}
    {% endif %}

<form method="post" action=""
      class="page-body">
    {% csrf_token %}
    <div class="appointment-user-info">
        <div class="appointment-user-info-title">
            <div id="paypal-button-container" class="paypal-button-container"></div>
        </div>

    </div>

<div class="checkout-info">
<div class="service-description-and-pay">
    <div class="service-details-title">{% trans "Order summary" %}</div>
<div class="service-description-content">
    <div class="img-container">
        <img src="{{ service.get_img_url }}"
             alt="{{ service.get_name }}"
             width="50px" height="auto">
    </div>
    <div class="item-name">{{ service.get_name }}</div>
<div>${{ service.get_amount_to_pay }}</div>
</div>

    <hr class="second-part">

<div class="service-payment">
<div class="subTotal">
    <div>{% trans "Subtotal" %}</div>
<div>${{ service.get_amount_to_pay }}</div>
</div>
<div class="salesTax">
    <div>{% trans "Sales Tax" %}</div>
    <div id="sales-tax-field">${{ fee_amount }}</div>
</div>
    <hr class="second-part">
<div class="total">
    <div>{% trans "Total" %}</div>
    <div id="sales-total-amount">${{ total_amount }}</div>
</div>
</div>
</div>
    <div class="securePayment">
        <?xml version="1.0"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" width="15px" height="15px"
             class="padlock">
            <path d="M 15 2 C 11.145666 2 8 5.1456661 8 9 L 8 11 L 6 11 C 4.895 11 4 11.895 4 13 L 4 25 C 4 26.105 4.895 27 6 27 L 24 27 C 25.105 27 26 26.105 26 25 L 26 13 C 26 11.895 25.105 11 24 11 L 22 11 L 22 9 C 22 5.2715823 19.036581 2.2685653 15.355469 2.0722656 A 1.0001 1.0001 0 0 0 15 2 z M 15 4 C 17.773666 4 20 6.2263339 20 9 L 20 11 L 10 11 L 10 9 C 10 6.2263339 12.226334 4 15 4 z"/>
        </svg>
        <p>Secure Checkout</p>
    </div>
</div>
</form>
</div>
</div>
{% endblock %}
{% block customJS %}
<script>
const object_id = "{{ object_id }}";
const id_request = "{{ id_request }}";

const createOrderURLTemplate = "{% url 'payment:create_order' object_id=0 %}";
const captureOrderURLTemplate = "{% url 'payment:capture_order' order_id='0' %}";

const createOrderURL = createOrderURLTemplate.replace("0", object_id);
let funding_source = "paypal";
paypal.Buttons({
    onClick: function (data, actions) {
        const fundingSource_ = data["fundingSource"]
        console.log("New funding source selected", fundingSource_);
        funding_source = fundingSource_;
    },
createOrder: function (data, actions) {
    console.log("Inside createOrder, funding source is still ", funding_source);
const createOrderURLWithFundingSource = `${createOrderURL}?funding_source=${funding_source}`;
    return fetch(createOrderURLWithFundingSource, {
        method: "POST",
    })
            .then((response) => response.json())
            .then((order) => {
                console.log("The order", order, JSON.stringify(order, null, 2));

                const salesTaxField = document.getElementById("sales-tax-field");
                salesTaxField.textContent = `$${order.fee}`;

                const salesTotalField = document.getElementById("sales-total-amount");
                salesTotalField.textContent = `$${order.total_amount}`;

                return order.id;
            });
},

    onApprove: function (data, actions) {
        const captureOrderURL = captureOrderURLTemplate.replace("0", data.orderID);

        return fetch(captureOrderURL, {
            method: "POST",
        })
                .then((response) => response.json())
                .then((orderData) => {
                    console.log("Capture result", orderData, JSON.stringify(orderData, null, 2));
                    window.location.href = `{% url 'payment:success_linked' object_id=object_id order_id='0' %}`.replace('/0', '/' + data.orderID);
                });
    },
}).render("#paypal-button-container");

document.addEventListener('DOMContentLoaded', function () {
    const messageElements = document.querySelectorAll('.alert-dismissible');
    setTimeout(function () {
        messageElements.forEach(function (element) {
            element.style.display = 'none';
        });
    }, 3000);
});
</script>

{% endblock %}

payment/templates/payment/payment_details.html
{% extends PAYMENT_BASE_TEMPLATE %}
{% load i18n %}
{% block title %}
Payment Success
{% endblock %}

{% block description %}
{% trans 'Your payment was successful! Thank you for your purchase.' %}
{% endblock %}

{% block body %}
<div class="main-content">
    <div style="margin: 0 auto; max-width: 900px; padding: 50px">
        <div class="payment-order">
            <p class="payment-notice payment-notice--{{ status }}">
                Payment status : <strong>{{ payment_info.get_status }}</strong>
            </p>
            <ul class="payment-order-overview payment-thankyou-order-details order_details">
                <li class="payment-order-overview__order order">
                    Order number: <strong>{{ payment_info.get_order_id }}</strong>
                </li>
                <li class="payment-order-overview__date date">
                    Date: <strong>{{ current_date }}</strong>
                </li>
                <li class="payment-order-overview__total total">
                    Total: <strong><span class="payment-Price-amount amount">
                    <span class="payment-Price-currencySymbol">
                        {{ payment_info.get_currency }}</span>{{ payment_info.get_total_amount }}</span></strong>
                </li>
                <li class="payment-order-overview__payment-method method">
                    Payment method: <strong>Check payments</strong>
                </li>
            </ul>
            <section class="payment-order-details">
                <h3 class="payment-order-details__title">Payment details</h3>
                <table class="payment-table payment-table--order-details shop_table order_details">
                    <thead>
                    <tr>
                        <th class="payment-table__product-name product-name">Service / Product</th>
                        <th class="payment-table__product-table product-total">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="payment-table__line-item order_item">
                        <td class="payment-table__product-name product-name">
                            <a href="#">
                                {{ linked_object }}
                            </a> <strong class="product-quantity"></strong></td>
                        <td class="payment-table__product-total product-total">
                            <span class="payment-Price-amount amount"><span class="payment-Price-currencySymbol">
                                {{ payment_info.get_currency }}</span>{{ payment_info.get_amount }}</span>
                        </td>
                    </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th scope="row">Subtotal:</th>
                        <td><span class="payment-Price-amount amount"><span class="payment-Price-currencySymbol">
                            {{ payment_info.get_currency }}</span>{{ payment_info.get_amount }}</span>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Taxes:</th>
                        <td><span class="payment-Price-amount amount"><span class="payment-Price-currencySymbol">
                            {{ payment_info.get_currency }}</span>{{ payment_info.get_fee }}</span>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Payment method:</th>
                        <td>Check payments</td>
                    </tr>
                    <tr>
                        <th scope="row">Total:</th>
                        <td><span class="payment-Price-amount amount"><span class="payment-Price-currencySymbol">
                            {{ payment_info.get_currency }}</span>{{ payment_info.get_total_amount }}</span>
                        </td>
                    </tr>
                    </tfoot>
                </table>
                <section class="payment-customer-details">
                    <h3>Customer details</h3>
                    <table class="payment-table payment-table--customer-details shop_table customer_details">
                        <tbody>
                        <tr>
                            <th>Email:</th>
                            <td>{{ user_email }}</td>
                        </tr>
                        <tr>
                            <th>Name:</th>
                            <td>{{ first_name }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <!--?<h3 class="payment-column__title">Billing address</h3>
                    <address>
                        An Luu
                        <br>An
                        <br>123 Luu Binh An
                        <br>Viet Nam
                        <br>Vietnam
                    </address>-->
                </section>
            </section>
        </div>
    </div>

</div>
{% endblock %}
{% block customCSS %}
<style>
    .main-content {
        font-size: 1rem;
        color: var(--color-primary-text);
        text-rendering: optimizelegibility;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: none;
        font-family: Arial, sans-serif
    }

    a {
        color: rgb(51, 51, 51);
        text-decoration: none;
        outline: 0;
        cursor: pointer
    }

    a:focus, a:hover {
        color: rgba(51, 51, 51, 0.8);
        -webkit-transition: all .2s ease-in-out;
        -moz-transition: all .2s ease-in-out;
        -ms-transition: all .2s ease-in-out;
        -o-transition: all .2s ease-in-out;
        transition: all .2s ease-in-out
    }

    :root {
        --color-primary: #00A5B4;
        --color-secondary: #C9DC08;
        --color-gray-100: #F7FAFC;
        --color-primary-text: #333;
        --color-gray-400: #CBD5E0;
        --color-red: #e41919;
        --color-border: #e1e3ea;
        --breakpoint-xs: 600px
    }

    .payment-info a {
        font-weight: 700;
        text-decoration: underline
    }

    .payment-notice--success {
        background: #e6f7e4;
        margin-top: 10px;
        padding: 15px;
        color: #39b44a;
        font-weight: 700;
        text-shadow: 1px 1px 0 rgba(255, 255, 255, .7)
    }

    .payment-notice--warning {
        background: #f7f3e4;
        margin-top: 10px;
        padding: 15px;
        color: #b49b39;
        font-weight: 700;
        text-shadow: 1px 1px 0 rgba(255, 255, 255, .7)
    }

    .payment-notice--danger {
        background: #f7e4e7;
        margin-top: 10px;
        padding: 15px;
        color: #b4394b;
        font-weight: 700;
        text-shadow: 1px 1px 0 rgba(255, 255, 255, .7)
    }

    .shop_table {
        width: 100%;
        margin-bottom: 2rem;
        max-width: 100%;
        background: #fff;
        border: 1px solid #e0e0e0;
        border-collapse: collapse;
        border-spacing: 0
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table [data-label] {
            position: relative;
            padding-left: 30%
        }

        .shop_table [data-label]:before {
            position: absolute;
            top: 0;
            left: 0;
            padding: 8px;
            content: attr(data-label);
            font-weight: 700
        }
    }

    .shop_table thead {
        background: #f2f2f2
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table thead {
            display: none
        }
    }

    .shop_table thead th {
        border-bottom: 1px solid #e0e0e0;
        padding: .7rem
    }

    .shop_table thead th:last-child {
        text-align: right
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tbody {
            display: block
        }
    }

    .shop_table tbody td {
        padding: .7rem;
        border-color: #f0f2f7
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tbody tr {
            border-bottom: 1px dotted rgba(0, 0, 0, .1);
            display: block
        }
    }

    .shop_table tbody tr th {
        text-align: left
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tbody tr th {
            display: block;
            padding: .7rem .7rem 0;
            text-align: left
        }
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tbody tr td {
            display: block;
            padding-top: .5rem;
            padding-bottom: .5rem
        }
    }

    .shop_table tbody tr td:last-child {
        text-align: right
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tbody tr td:last-child {
            text-align: left
        }
    }

    .shop_table tfoot {
        border-top: 1px solid #f0f2f7;
        background: #fafafa
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tfoot {
            display: block
        }
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tfoot tr {
            display: flex
        }
    }

    .shop_table tfoot th {
        padding: .7rem;
        text-align: right
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tfoot th {
            width: 30%;
            padding-top: .2rem;
            padding-bottom: .2rem;
            text-align: left
        }
    }

    .shop_table tfoot td {
        padding: .7rem;
        text-align: right;
        width: 10%
    }

    @media (max-width: var(--breakpoint-xs)) {
        .shop_table tfoot td {
            width: 70%;
            padding-top: .2rem;
            padding-bottom: .2rem;
            text-align: left;
            padding-left: 0
        }
    }

    .payment-order-overview {
        background: #f8f8f8;
        list-style: none;
        margin: 2rem 0;
        padding: 0;
        position: relative;
        display: flex;
        align-items: center
    }

    @media (max-width: 600px) {
        .payment-order-overview {
            display: block
        }
    }

    .payment-order-overview:after, .payment-order-overview:before {
        background: -webkit-linear-gradient(transparent 0, transparent 0), -webkit-linear-gradient(135deg, #f8f8f8 33.33%, transparent 33.33%), -webkit-linear-gradient(45deg, #f8f8f8 33.33%, transparent 33.33%);
        content: "";
        display: block;
        position: absolute;
        top: -16px;
        left: 0;
        width: 100%;
        height: 16px;
        background-size: 0 100%, 16px 16px, 16px 16px
    }

    .payment-order-overview:after {
        top: auto;
        bottom: -16px;
        -webkit-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        transform: rotate(180deg)
    }

    .payment-order-overview li {
        padding: 1em 1.618em;
        font-size: .8em;
        width: 25%;
        text-transform: uppercase;
        border-right: 1px dotted #e3e3e3;
        text-align: center
    }

    @media (max-width: 600px) {
        .payment-order-overview li {
            width: auto;
            text-align: left;
            padding: 10px 0;
            margin: 0 15px;
            border-right: none;
            border-bottom: 1px dotted #e3e3e3
        }

        .payment-order-overview li:last-child {
            border-bottom: none
        }
    }

    .payment-order-overview li:last-child {
        border-right: none
    }

    .payment-table--customer-details {
        border: none
    }

    .payment-table--customer-details tbody th {
        background: #f8f8f8;
        padding-left: 25px
    }

    @media (max-width: 600px) {
        .payment-table--customer-details tbody th {
            width: 100%;
            display: block;
            text-align: left;
            padding-top: 5px;
            padding-bottom: 5px
        }
    }

    .payment-table--customer-details tbody td {
        background: #fdfdfd;
        padding-left: 25px;
        text-align: left !important
    }

    .shop_table.payment-table--order-details {
        box-shadow: 0 0 5px rgba(57, 180, 74, .1)
    }

    .shop_table.payment-table--order-details thead {
        background: #000;
        color: #fff
    }

    .shop_table.payment-table--order-details thead th {
        border-bottom: none;
        font-weight: 400;
        font-size: .9rem
    }

    .shop_table.payment-table--order-details thead th.product-name {
        text-align: left
    }

    .shop_table.payment-table--order-details tbody td {
        border-color: #f0f2f7
    }
</style>
{% endblock %}